### ISSUE TITLE
py3.5/3.6 incompatibility

### ISSUE THREAD

**Issue by xrotwang** [clld/crossgram#1]
[`fromisoformat`](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat) is new in py 3.7 - so should not be used for clld apps (yet):

```python
  File "/home/forkel/venvs/crossgram/crossgram/crossgram/lib/cldf.py", line 375, in load
    published = date.fromisoformat(contrib_md['published'])
AttributeError: type object 'datetime.date' has no attribute 'fromisoformat'
```

**Comment by xrotwang** [comment]
nice. can run the app locally, now. wild logo, though.

**Comment by johenglisch** [comment]
Oh, right -- I keep forgetting about that. (<_<)"
