### ISSUE TITLE
"Topics" page, column showing related parameters

### ISSUE THREAD

**Issue by haspelmath** [clld/crossgram#10]
The Topics page (https://crossgram.clld.org/topics) currently shows Croft and Wikipedia counterparts, but these two are not very important (they should be part of Grammaticon, once that is more advanced). Instead, there should be a column listing related parameters, e.g. for "A-argument", the five parameters listed here: https://crossgram.clld.org/topics/AARG – And actually, there is no need to list those topics that are not related to any of the parameters.

**Comment by johenglisch** [comment]
I added a *Parameters* column to the table of topics.  Currently it does not distinguish between L and C parameters (it just shows both if available).

**Comment by haspelmath** [comment]
Thank you!
