### ISSUE TITLE
remove "meaning" table from Brad-type databases

### ISSUE THREAD

**Issue by haspelmath** [clld/crossgram#12]
Brad-type databases have a "meanings" table, which is not relevant for CrossGram – it will be ignored in future exports.

**Comment by johenglisch** [comment]
I removed the code that reads the meaning table from the [processing code](https://github.com/cldf/ditrans2cldf). So far, I only recreated the CLDF data for *Ditransitives*.  The others will just get their update whenever we work on them.

**Comment by haspelmath** [comment]
Many thanks!
