### ISSUE TITLE
example pages "Ditransitives"

### ISSUE THREAD

**Issue by haspelmath** [clld/crossgram#3]
In "Ditransitives" and perhaps more generally, the example page numbers are missing: https://matthew.clld.org/crossgram/contributions/malchukovditransitives#texamples. The exported "Examples.xlsx" table has both a "Reference_ID" column and a "Reference_pages" column". Thanks!

**Comment by haspelmath** [comment]
On the languages page, the drop-down menu for the “family” column contains all Glottolog families, but ideally, it would contain only those families that are in fact represented in the contribution. For example, in the Reesink contribution, these would only be Papuan families: https://crossgram.clld.org/contributions/reesinkgive#tlangs

**Comment by johenglisch** [comment]
That was a bug in the cldf creation code. I fixed it over there.
