### ISSUE TITLE
drop-down menu

### ISSUE THREAD

**Issue by haspelmath** [clld/crossgram#5]
On the languages page, the drop-down menu for the “family” column contains all Glottolog families, but ideally, it would contain only those families that are in fact represented in the contribution. For example, in the Reesink contribution, these would only be Papuan families: https://crossgram.clld.org/contributions/reesinkgive#tlangs

**Comment by johenglisch** [comment]
I fixed that in https://github.com/clld/crossgram/commit/881cd331501ac68f6482ffda472f93cc9fbaec55. Just hadn't deployed it to the web server, yet (I did now).
