### ISSUE TITLE
Ditransitives > Ditransitive constructions

### ISSUE THREAD

**Issue by haspelmath** [clld/crossgram#7]
Siehe E-mail vom 23.4., unten kopiert. Addendum: Der Titel sollte jetzt "Ditransitive constructions" sein (nicht mehr "Ditransitives"), und die Jahreszahl ist 2024 (Autoren sind Malchukov & Haspelmath, das ist richtig).

********
Lieber Johannes,

Ich habe jetzt einen neuen Export der Ditransitives-Datenbank gemacht, der so weit fertig ist, dass er in die öffentliche Version (https://crossgram.clld.org/) hochgeladen kann. Ich werde in den nächsten Wochen noch weiter daran arbeiten, aber spätestens im Juli mache ich Schluss – dann ist es so fertig, wie es halt werden kann.

Für August oder September würde ich dann endlich die "Grand Opening" planen, d.h. wir gehen aus der Soft-Launch-Phase (oder Beta-Phase) in die Normalphase über (die Termini habe ich erst vor kurzem gelernt: https://svaerm.com/blog/soft-launch/).

Vielen Dank,

und bis Donnerstag 11:30h,

Martin

**Comment by johenglisch** [comment]
https://matthew.clld.org/crossgram/contributions/malchukovditransitives
