### ISSUE TITLE
TDIR (Volker Gast)

### ISSUE THREAD

**Issue by haspelmath** [clld/crossgram#8]
E-mail vom 19.4., hier kopiert:

Lieber Johannes,

Ich bin jetzt mit dem Datensatz "Intensifiers and reflexives" soweit – siehe die drei Dateien anbei.

Die Referenzen waren ja noch gar nicht da, und außerdem gibt es jetzt 5 statt bisher 12 L-parameters (https://matthew.clld.org/crossgram/contributions/gasttdir#tlparams).

Die drittletzte und letzte (paradigms, repr) fallen ganz weg. Die Parameter, die bleiben, sind ADN, EXC ("ave"), REFL, OWN, und SFP.

Die Informationen in "otherrefl" kommen in die Kommentare von REFL, und "sort", "lex", "otherint" und "comments" habe ich manuell in eine einzige Kommentarspalte eingefügt, die in die Kommentare von ADN.

Vielen Dank!

Martin

**Comment by johenglisch** [comment]
Hab die aktualisierte Fassung hochgeladen.  Was mir aufgefallen ist, sind viele Werte, die einfach mit `%` gefüllt sind (sieht man hier gut: <https://matthew.clld.org/crossgram/parameters/gasttdir-SFP#2/21.6/147.9>).

Mein Bauchgefühl sagt mir, daß das Nullwerte sind, die man einfach rausfiltern kann.

**Comment by haspelmath** [comment]
Danke!
